version: '3.5'
services:
    qbittorrrent:
        container_name: qBittorrrent
        build: .
        volumes:
            # - $PWD/downloads:/opt/download
            - $PWD/root:/root
        ports:
            - 8080:8080
        tty: true
        restart: always
        networks:
                download:


networks:
    download:
        name: "download_network"
        driver: "bridge"
