version: '3.5'

services:
  qbittorrrent:
    container_name: qBittorrrent
    image: captain686/qbittorrent
    volumes:
      - $PWD/root:/root
      - $PWD/downloads:/opt/download
    tty: true
    restart: always
    network_mode: host

volumes:
  root:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/root
