name: Docker Image CI

on:
  # push:
  #   branches: [ "main" ]
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  UPDATE: false

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: check update
      run: |
        export update=false
        chmod 777 check.sh
        export update=$(./check.sh)
        echo "UPDATE=$update" >> $GITHUB_ENV
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      if: ${{ env.UPDATE == 'true' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/qbittorrent:latest

    - name: git push
      if: ${{ env.UPDATE == 'true' }}
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add .
        git commit -m "🚀 $(cat qbittorrent-nox_version)"

    - name: push changes
      if: ${{ env.UPDATE == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
